name: Build Docker Image
on:
  push:
    branches:
      - main
jobs:
    build_docker_image:
      needs: build
      name: build and push docker image to docker hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: login to docker hub
          id: docker-hub
          env:
            username: ${{secrets.DOCKER_HUB_USER}}
            password: ${{secrets.DOCKER_HUB_PAT}}
          run: |
            docker login -u $username -p $password 
        - name: build the docker image
          id: build-docker-image
          run: |
            ls -la 
            docker build . -f ./ServiceExample/Dockerfile -t ${{secrets.DOCKER_HUB_USER}}/service-example:latest
        - name: push the docker image
          id: push-docker-image
          run: docker push ${{secrets.DOCKER_HUB_USER}}/service-example:latest
